export interface Car{
    id:number,
    name:string;
    carCondition:string;
    color:string;
    description:string;
    fuel:string;
    imagePath:string;
    isAvailableForRental:boolean;
    isAvailableForReserve:boolean;
    isDeleted:boolean;
    make:string;
    manufactureYear:number;
    mileage:number;
    model:string;
    modelVariant:string;
    price:number;
    reservationFee:number;
    transmission:string;
}